// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('null division', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('null division', async function() {
    // Test name: null division
    // Step # | name | target | value
    // 1 | open | https://safatelli.github.io/tp-test-logiciel/assets/calc.html | 
    await driver.get("https://safatelli.github.io/tp-test-logiciel/assets/calc.html")
    // 2 | setWindowSize | 1440x810 | 
    await driver.manage().window().setRect({ width: 1440, height: 810 })
    // 3 | type | id=num1 | 0
    await driver.findElement(By.id("num1")).sendKeys("0")
    // 4 | select | id=operator | value=division
    {
      const dropdown = await driver.findElement(By.id("operator"))
      await dropdown.findElement(By.css("*[value='division']")).click()
    }
    // 5 | type | id=num2 | 0
    await driver.findElement(By.id("num2")).sendKeys("0")
    // 6 | click | css=button | 
    await driver.findElement(By.css("button")).click()
    // 7 | assertText | id=result | Résultat : NaN
    assert(await driver.findElement(By.id("result")).getText() == "Résultat : NaN")
  })
})
