// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('panier', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('panier', async function() {
    // Test name: panier
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://www.demoblaze.com/")
    // 2 | click | id=login2 | 
    await driver.findElement(By.id("login2")).click()
    // 3 | click | id=loginusername | 
    await driver.findElement(By.id("loginusername")).click()
    // 4 | type | id=loginusername | omar-mahmoud-2002
    await driver.findElement(By.id("loginusername")).sendKeys("omar-mahmoud-2002")
    // 5 | click | id=loginpassword | 
    await driver.findElement(By.id("loginpassword")).click()
    // 6 | type | id=loginpassword | pwd
    await driver.findElement(By.id("loginpassword")).sendKeys("pwd")
    // 7 | click | css=#logInModal .btn-primary | 
    await driver.findElement(By.css("#logInModal .btn-primary")).click()
    // 8 | click | linkText=Samsung galaxy s7 | 
    await driver.findElement(By.linkText("Samsung galaxy s7")).click()
    // 9 | store | Samsung galaxy s7 | product
    vars["product"] = "Samsung galaxy s7"
    // 10 | click | linkText=Add to cart | 
    await driver.findElement(By.linkText("Add to cart")).click()
    // 11 | assertAlert | Product added. | 
    assert(await driver.switchTo().alert().getText() == "Product added.")
    // 12 | click | id=cartur | 
    await driver.findElement(By.id("cartur")).click()
    // 13 | assertText | css=td:nth-child(2) | ${product}
    assert(await driver.findElement(By.css("td:nth-child(2)")).getText() == "vars[\"product\"]")
    // 14 | click | linkText=Delete | 
    await driver.findElement(By.linkText("Delete")).click()
    // 15 | click | id=logout2 | 
    await driver.findElement(By.id("logout2")).click()
  })
})
