// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('signin', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('signin', async function() {
    // Test name: signin
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://www.demoblaze.com/")
    // 2 | setWindowSize | 1920x1056 | 
    await driver.manage().window().setRect({ width: 1920, height: 1056 })
    // 3 | click | id=login2 | 
    await driver.findElement(By.id("login2")).click()
    // 4 | click | id=loginusername | 
    await driver.findElement(By.id("loginusername")).click()
    // 5 | type | id=loginusername | omar-mahmoud-2002
    await driver.findElement(By.id("loginusername")).sendKeys("omar-mahmoud-2002")
    // 6 | click | id=loginpassword | 
    await driver.findElement(By.id("loginpassword")).click()
    // 7 | type | id=loginpassword | pwd
    await driver.findElement(By.id("loginpassword")).sendKeys("pwd")
    // 8 | click | css=#logInModal .btn-primary | 
    await driver.findElement(By.css("#logInModal .btn-primary")).click()
    // 9 | assertText | id=nameofuser | Welcome omar-mahmoud-2002
    assert(await driver.findElement(By.id("nameofuser")).getText() == "Welcome omar-mahmoud-2002")
    // 10 | click | id=logout2 | 
    await driver.findElement(By.id("logout2")).click()
  })
})
