// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('success', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('success', async function() {
    // Test name: success
    // Step # | name | target | value
    // 1 | open | https://safatelli.github.io/tp-test-logiciel/assets/hello.html | 
    await driver.get("https://safatelli.github.io/tp-test-logiciel/assets/hello.html")
    // 2 | setWindowSize | 1440x810 | 
    await driver.manage().window().setRect({ width: 1440, height: 810 })
    // 3 | click | id=username | 
    await driver.findElement(By.id("username")).click()
    // 4 | type | id=username | omar besbes
    await driver.findElement(By.id("username")).sendKeys("omar besbes")
    // 5 | click | css=button | 
    await driver.findElement(By.css("button")).click()
    // 6 | assertText | id=message | Bonjour, mahmoud nefzi !
    assert(await driver.findElement(By.id("message")).getText() == "Bonjour, mahmoud nefzi !")
  })
})
